### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by riyenas0925** [Study-Mornda/Java_PlayGround#1]
### 스터디 방식
1. 요구사항을 보고 자신의 방식으로 구현합니다.
2. 코드리뷰를 서로 진행합니다.
3. 코드리류를 바탕으로 리펙터링을 진행합니다.
3. 해설 강의를 듣습니다.
4. 다시 요구사항을 보고 자신의 방식으로 구현합니다.
5. 각자 구현하면서 느낀 점을 공유합니다.

**Comment by kimhanui** [comment]
Readme.md 파일은 어느 정도 정리되었으니 이 이슈는 Close해도 될 것 같습니다~
확인하면 Close해주세요 @riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui 넵 close 합니다~
